### ISSUE TITLE
`topkg test` doesn't support -n

### ISSUE THREAD

**Issue by talex5** [dbuenzli/topkg#100]
If I have multiple packages, I should be able to test all of them:

```
$ ocaml pkg/pkg.ml test -n prometheus-app
pkg.ml: [ERROR] unknown option `-n'
```

(from https://github.com/ocaml/opam-repository/commit/d1b35d45f63e085ceaae4fdbf4ee2093888ae785#commitcomment-20766305)

**Comment by dbuenzli** [comment]
I added the flag for consistency but in fact you don't need it. When you build a package with `-n` with tests, `topkg` writes your test specification in `_build/_topkg.test` it is then perfectly able to run them. You can test this with the current `topkg` in `prometheus-app`, `ocaml pkg/pkg.ml` test` or `ocaml pkg/pkg.ml test test` will perfectly run them.

**Comment by dbuenzli** [comment]
However now that I'm on the way I will make that you can test packages in parallel which is not possible at the moment (since `_build/_topkg.test` if you build two different package).

**Comment by dbuenzli** [comment]
So I did that. Note that running `topkg test` will no longer run the tests of the last build package. It will now run the tests of the default package. In other words `topkg test` now fully mirrors the way `topkg build` work.
