### ISSUE TITLE
new release compatible with cmdliner 1.0 and opam-lib 1.3.1?

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#105]
Everything is said in the title.

**Comment by dbuenzli** [comment]
I'm waiting on @altgr's input on the new opam v2 build instructions [here](https://github.com/dbuenzli/topkg/issues/79#issuecomment-283158194).

**Comment by dbuenzli** [comment]
On its way in https://github.com/ocaml/opam-repository/pull/8705
