### ISSUE TITLE
0.9.0 release tarball corrupt

### ISSUE THREAD

**Issue by dra27** [dbuenzli/topkg#107]
```
dra@bean:~$ tar -xjf topkg-0.9.0.tbz 

bzip2: (stdin): trailing garbage after EOF ignored
```

The archive appears to be fine, though, having compared it with a git clone.

**Comment by dbuenzli** [comment]
Strange, the error doesn't happen on macOS, but I can reproduce on linux.

**Comment by dra27** [comment]
That's disturbing! I'm getting the same error with Cygwin (although the log above was Linux)

**Comment by dra27** [comment]
Resource forks?

**Comment by dbuenzli** [comment]
In any case the tarballs should be reproducible and in this case they are not I get an md5 of `626db1f29896221af7ed0b34a04d8c15` on linux and `1700991f570b9aaf49e6aad7d886e154` on macOS.

**Comment by dbuenzli** [comment]
The `tar` archives themselves are however.

**Comment by dbuenzli** [comment]
And rebzipping them manually yields the same md5 (the linux one). I suspect there may be a bug in `bos` on [this run form](https://github.com/dbuenzli/topkg/blob/master/src-care/topkg_care_archive.ml#L136).

**Comment by dbuenzli** [comment]
Argh. Can't reproduce anymore `topkg distrib` in `topkg` now gives me the same `tbz` on linux and macos.

**Comment by dbuenzli** [comment]
Ah I think I found the problem if I 

```
echo "hey" >> _build/topkg-0.9.0.tbz
```

and redo a `topkg distrib` the `md5` is not the same as if I `topkg clean && topkg distrib`. I vaguely remember that during the `0.9.0` publication I redid the tagging + tarball once before it hit the internet which if larger could have lead to this situation. 

It seems `O_TRUNC` is missing [here](https://github.com/dbuenzli/bos/blob/master/src/bos_os_cmd.ml#L139) in `bos` if we don't append...

**Comment by dbuenzli** [comment]
@dra27 Thanks for the report. 

Note that while `tar -xjf` did not surface the `bzip2` error message, a direct usage of  `unbzip2` did reveal the same error message on macOS. 

The commit message of faed66f has the exact scenario where this could happen. I have [published] (https://github.com/ocaml/opam-repository/pull/8740) bos 1.5.0 which along with [these constraints](https://github.com/ocaml/opam-repository/pull/8741) will prevent this from happening.

**Comment by dra27** [comment]
No problem - sometimes bugs surface in the weirdest circumstances!
