### ISSUE TITLE
Please break the cyclic build dependency

### ISSUE THREAD

**Issue by infinity0** [dbuenzli/topkg#116]
Continuing from https://github.com/dbuenzli/topkg/issues/115#issuecomment-315915323

> That's precisely what you don't understand. The cost is much lesser for me that way, I manage approximatively 30 OCaml packages and I need to be efficient in this (see [here](http://ocamllabs.io/projects/2017/02/23/topkg.html) for more on this). With appropriate tooling on the debian side which is perfectly possible by using the `opam v2` API on I don't think it will incur a cost there.
> [..]
> Maybe you should be a little bit more open minded and try to understand why things are done in a certain manner before starting yelling to much and "explain" me things and try to impose your viewpoint about things.

Maybe you should stop acting with such a bullshit superiority complex. You think you're not wasting *my* time? If you had explained to me details of your issues, instead of coming out with bullshit comments like "This seems rather a debian packaging mistake", "I challenged your intuitions", we could have had a proper conversation about the technical details of your concerns.

I maintain [44 Debian packages](https://qa.debian.org/developer.php?login=infinity0). Actually the true number is a bit more, one of them has about [180 build dependencies](https://packages.debian.org/source/sid/sagemath) so in practise I have to deal with those too. Incidentally the sagemath guys were nice enough to listen to my points about cyclic build-dependencies, they had a similar issue last year which they fixed after I [asked them to](https://groups.google.com/forum/#!topic/sage-devel/s8yeEPK_9zU).

**Comment by dbuenzli** [comment]
As I suspected, the pleasantly unhysterical person in charge of packaging `topkg` downstream perfectly understands there is no circular dependency. See the discussion [here](https://lists.debian.org/debian-ocaml-maint/2017/07/msg00199.html) and follow-ups.
