### ISSUE TITLE
`topkg distrib` never finishes

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/topkg#128]
Doing `topkg distrib --verbose` on the project https://github.com/Chris00/ocaml-crlibm stalls after the line:
```
pkg.ml: [INFO] Watermarked src/crlibm/docs/latex/fig_scs/exponent_representation.eps
```
(BTW, the directory `src/crlibm/docs` needs not be put in the tarball.  Is there a way to tell that to _topkg_?)

**Comment by dbuenzli** [comment]
> (BTW, the directory src/crlibm/docs needs not be put in the tarball. Is there a way to tell that to topkg?)

Yes, see the `exclude_paths` argument of [`Pkg.distrib`](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALdistrib).

I suspect you are running into https://github.com/samoht/dune-release/pull/11

**Comment by dbuenzli** [comment]
> Yes, see the exclude_paths argument of Pkg.distrib.

(See uucp in the [menagerie](http://erratique.ch/software/topkg/doc/Topkg.html#menagerie)) for an example.

**Comment by Chris00** [comment]
Thanks — that was quick to do with your indications.

Maybe you want to exclude `.ps` and `.eps` files from watermarking by default??

**Comment by dbuenzli** [comment]
> Maybe you want to exclude .ps and .eps files from watermarking by default??

Certainly a good idea.
