### ISSUE TITLE
Publishing on Github

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/topkg#132]
I do not know whether this is just me but, while publishing on Github creates the files in the branch `gh-pages`, they cannot be consulted online (Github returns 404).  I have checked that creating an index file at the root of the `gh-pages` branch does work.

**Comment by dbuenzli** [comment]
Are you using `jbuilder` if that the case please see https://github.com/dbuenzli/topkg/issues/129

**Comment by Chris00** [comment]
I do.  Thanks for the link.
