### ISSUE TITLE
Should topkg be on OPAM?

### ISSUE THREAD

**Issue by jordwalke** [dbuenzli/topkg#16]
There might be some issues with embedding the `topkg.ml` file into other repos which might have conflicting licenses (IANAL).  Is it possible to somehow allow `topkg` to be an `OPAM` dependency?

**Comment by dbuenzli** [comment]
> There might be some issues with embedding the topkg.ml file into other repos which might have conflicting licenses (IANAL).

I don't see any problem with this. But yes topkg will soon become an opam package for package maintainability reasons.

**Comment by samoht** [comment]
A horde of desperate OCaml developers is looking forward to consume that new opam package.

**Comment by dbuenzli** [comment]
https://github.com/ocaml/opam-repository/pull/6588
