### ISSUE TITLE
Automatic generation of META file at pin/release time

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#18]
It shouldn't be too hard to support the simple cases which will cover 98% of the packages out there. However we'll need an `opam` with https://github.com/ocaml/opam/issues/2254 to add some data to guide the process.

**Comment by paurkedal** [comment]
I think it would be useful to also generate an analogous `META` file for internal use when building programs and tests.  My reasoning is:

- Findlib gets the link order right in presence of multiple internal libraries, while the alternative `Ocamlfind_plugin.ocaml_lib` is unaware of dependencies.
- It gives an opportunity to test the external dependencies by omitting them from the `_tags` specifications of the tests.
- Easier: `myocamlbuild.ml` is not needed just to declare the libraries, and `_tags` specifications are analogous as for external libraries.

The internal `META` should use different library names, e.g. prefixed by `build.`, to avoid conflict with the installed package.  The source layout probably needs to mirror the installed layout for this to work.

**Comment by dbuenzli** [comment]
> but generating them from myocamlbuild.ml worked out nicely.

Indeed it seems that the build system is in a better position to generate the `META` file than `topkg` since a well written `_tags` file can have the precise `ocamlfind` dependencies for building a library. `ocamlfind` does not live as a concept in `topkg`'s install description. Build configuration is managed by `Conf.with_pkg` but this is meant to represent OPAM packages.  

/cc @samoht.

**Comment by paurkedal** [comment]
Well, I generated it from the exported `META` by a simple substitution, so it's not much use here.  But a properly written ocamlbuild plugin could subsume both #27 and this issue. Lacking that, linting the META requirements would still be very nice, I don't mind so much writing it, as long as it's verified.

**Comment by dbuenzli** [comment]
> Lacking that, linting the META requirements would still be very nice, I don't mind so much writing it, as long as it's verified.

The thing is that to properly lint the `requires` w.r.t. the build system (i.e. the `_tags` file), i.e. make sure they are *correct*; you need to have a precise `_tags` and I'd say that at that point you are better off creating the META file from the build system.

**Comment by paurkedal** [comment]
I see your point.  And Topkg should probably still look at the `_tags` rather than the generated META files, since it may contain additional build-dependencies for tests, programs, and ppx.

**Comment by dbuenzli** [comment]
In fact I'm wondering if it's possible to invoke the ocamlbuild API by myself to parse the `_tags` and try a best effort `META` file generation (in the sense rather than try to express this in a `myocamlbuild.ml`)

**Comment by rgrinberg** [comment]
ocamlbuild allows you to specify tags outside the _tags file however. You can use command line options, and you can also use functions like `tag_file` from myocamlbuild.ml.

It would be great if this is doable in a non fragile way.

**Comment by dbuenzli** [comment]
Topkg is in maintenance mode no new features will be added.
