### ISSUE TITLE
Extend browser reload support.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#20]
For now the full browser reload strategy is only supported on osx with chrome and safari. Help for extending support along [the documentation](http://erratique.ch/software/topkg/doc/Topkg_care.Browser.html) is welcome. 

* osx support for firefox and other browsers
* linux support beyond `xdg-open`  
* windows everything.

**Comment by avsm** [comment]
What's the process to build the documentation without opening a browser?  I'm building in a minimal Linux container, and this happens:

```
dfile:debian:x86_64:4.02.3:~/src/dockerfile$ ./build doc
topkg: [ERROR] ocamlbuild: no such command
dfile:debian:x86_64:4.02.3:~/src/dockerfile$ topkg doc --dev
topkg: [ERROR] ocamlbuild: no such command
```

**Comment by dbuenzli** [comment]
You are running [into this issue](https://github.com/dbuenzli/topkg/issues/39) which is solved in `bos` master.

**Comment by avsm** [comment]
Confirmed, thanks!

**Comment by dbuenzli** [comment]
Browser reload support has been forked into a separate package. This issue is now tracked there https://github.com/dbuenzli/webbrowser/issues/1
