### ISSUE TITLE
`topkg doc` eventually move to a forward looking scheme 

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#24]
As noted in the man page:

```
    `P "$(b,WARNING.) The way this command works is at the moment
        moment very ad-hoc and ocamlbuild specific. It will
        change in the future.";
```

The future involves `odoc`. No plans to change this before.

**Comment by dbuenzli** [comment]
e8d7220bfaa3494f3d02ae tries to steal `odig`'s `ocamldoc` stylesheet whenever the latter is installed. This avoid having to have a stylesheet in each repo and shows you how it will be rendered by `odig`'s ocamldoc path.

**Comment by samoht** [comment]
Would it make sense to steall the `build-doc` command defined in the `opam` file instead? More generally maybe `topkg` could still the build command defined in the opam file in the distrib build tests.

**Comment by dbuenzli** [comment]
Topkg is in maintenance mode no new features will be added.
