### ISSUE TITLE
Cannot `exec` the `type` shell built-in

### ISSUE THREAD

**Issue by paurkedal** [dbuenzli/topkg#39]
I get errors abount commands not found when running `topkg`, e.g.
```
$ topkg doc
topkg: [ERROR] ocamlbuild: no such command
```
The problem is that `Topkg_os.Dir.test_cmd` tries to test for the presence of commands by executing `type`, which is a shell built-in.  The `which` command could be used instead.

**Comment by dbuenzli** [comment]
> The problem is that Topkg_os.Dir.test_cmd tries to test for the presence of commands by executing type, which is a shell built-in.

I guess you mean `Topkg.OS.Cmd.exists`, that one though goes through `Sys.command` which works. However `topkg` the tool uses `Bos.OS.Cmd.exists` and you are running into https://github.com/dbuenzli/bos/issues/52. It's nice however to give me a tool on Linux (I guess) that allows this, it is however unfortunate that this is not a standard POSIX tool.

**Comment by paurkedal** [comment]
You're right, I didn't read the definition of `exec`.

**Comment by paurkedal** [comment]
Works when pinning `bos` to the dev repo, so closing this.  Thanks!

**Comment by dbuenzli** [comment]
Reopening until bos is released so that people see it.

**Comment by paurkedal** [comment]
Sorry, there is a reason closing issues should be left to the maintainer.

**Comment by dbuenzli** [comment]
A new release of bos has been submited to the opam repo /cc @avsm.
