### ISSUE TITLE
Installed OPAM files need the version number

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#49]
One of the steps `topkg` takes to gradually introduce the idea of using OPAM files as the package metadata format (also outside OPAM managed installs) is to have them in the distribution and automatically install them in `$(opam config var PKG:lib)`. One of the problem at the moment though is that these files lack the distribution version number.

Here are a few ways this could be solved:

1. Simply have `version: "%%VERSION%%"` in the OPAM files in the dev repo, this will be substituted appropriately by the watermarking process. This has the following problems: 
   1. We currently simply use the `opam` file of the repo on `topkg opam pkg` so the field would need 
       to be filtered out. I'm not very keen on having to butcher OPAM files, although the v2 API may help 
       with this.
   2. I don't remember the details but I think this would affect the pinning process we'd get `test.%%VERSION%%` pins which would certainly break version comparison and be very unpleasant to the eye. If that's the case then this solution is ruled out.

2. Hack. We could simply append a proper `version: ` field after the watermarking ran and before invoking the user distribution massage hook, to all OPAM files mentioned in `Pkg.describe` before running the watermarking process.

**Comment by samoht** [comment]
I am not sure why you need the version number, but 1. is indeed not very nice as it will break the pin workflow. So yes, I don't see how you could do better than 2.

**Comment by dbuenzli** [comment]
> I am not sure why you need the version number, but 1.

Imagine that you have a non OPAM managed install (e.g. system install) and want to replicate the output of `ocamlfind list`. Basically I need the version number like you have the `version` field in `META`s.

**Comment by dbuenzli** [comment]
@samoht Another benefit of solving this is that you can then `path` pin the distribution tarball and get the correct version constraint. I'm going for 2.

**Comment by dbuenzli** [comment]
Done.

**Comment by dbuenzli** [comment]
This triggers annoying warnings on `topkg distrib`.
```
Warnings found in ~/sync/repos/fmt/_build/fmt-0.8.0-2-g8e65774/opam:
  warning  5: Unexpected version 0.8.0-2-g8e65774, the directory name or pinning implied 8.0-2-g8e65774
```
We should simply try to filter it out, it is unclear whether `opam lint` will be configurable in the future ( https://github.com/ocaml/opam/issues/2448).

**Comment by AltGr** [comment]
`opam lint` should definitely be configurable (the warnings were numbered to that purpose).

On the pinning workflow, you would indeed get an annoying `pkg.%%VERSION%%` by default, but note that you can now do `opam pin add pkg.somever TARGET` to force the version to be used, independently of the opam file.

**Comment by dbuenzli** [comment]
> opam lint should definitely be configurable (the warnings were numbered to that purpose).

Also paying more attention to the exit codes would be nice.

> On the pinning workflow, you would indeed get an annoying pkg.%%VERSION%% by default

Yeah. In the end I think its good if people don't have versions at all in the OPAM files of their repo and I'm not too unhappy about 3c7bb26edd3adc7ccd. Though the latter could maybe check if there's a preexisting 'version:' before prepending a new one or we could ask this not to be performed in `Topkg.Pkg.opem_file`.

Btw. I'm going to need more and more OPAM's file parser as a simple separate library where are we on that front ?
