### ISSUE TITLE
support for ocamlbuild plugin-tag ??

### ISSUE THREAD

**Issue by hhugo** [dbuenzli/topkg#5]
see https://github.com/hhugo/reactiveList/commit/e4913cfdd3a6cb0d87d00cb1b4be9077c3dca134

**Comment by dbuenzli** [comment]
This is problematic for my in a variety of contexts: 

https://github.com/dbuenzli/mtime/issues/1
https://github.com/dbuenzli/jsont/issues/3
https://github.com/dbuenzli/useri/blob/master/myocamlbuild.ml

Could also be here https://github.com/dbuenzli/vg, but I'm not yet using the plugin there.

It's seems that the notion of ocamlbuild plugin is not very compositional (here in the sense it's not easy to enable/disable).

**Comment by dbuenzli** [comment]
Not sure I'm going to fix this. Maybe it will be simpler to switch to assemblage at some time `t` in the future.

**Comment by dbuenzli** [comment]
Well actually if the project only uses `myocamlbuild.ml` for `js` (e.g. in `jsont`, `vg`) then it should be possible to conditionalize the `builder` argument on the presence of the `jsoo` key. 

However when `myocamlbuild.ml` is used both for compiling `C` stubs and `js` (`mtime`, `useri`) then it's hopeless, fundamentally `ocamlbuild` should allow to specify multiple plugins on the command line.

**Comment by dbuenzli** [comment]
Another solution to this problem would be to distribute ocaml plugins separatly from the software they are supposed to support. So that we can depend on the build rules without depending on the software itself. See https://github.com/ocsigen/js_of_ocaml/issues/360

**Comment by dbuenzli** [comment]
While this is a little bit dirty it is possible in practice to completely change the description dynamically based on the environment, see for example how this is done in the [`uchar` package](https://github.com/ocaml/uchar/blob/3c044fd9facb934d80881f05fcf29bac2a54c22b/pkg/build.ml). The upcoming topkg overhaul also comes with pre-build hooks which among other things should allow to slightly tweak the build system according to the environment before invoking it.

**Comment by dbuenzli** [comment]
My last comment was mainly responding to my owns. Regarding the initial request, the builder specification already changed quite a bit since then and it is already easy to add arguments to ocamlbuild with the [current version of the script](https://github.com/dbuenzli/topkg/blob/a2f3f195192d9bc78ed2839e892ae8a80bc0f418/pkg/topkg.ml#L61-L72).
