### ISSUE TITLE
topkg-care should depend on a specific version of topkg

### ISSUE THREAD

**Issue by stedolan** [dbuenzli/topkg#51]
I just upgraded to `topkg` 0.7.4 to get shiny new testsuite-building abilities. I forgot to upgrade `topkg-care`, which crashed when `topkg-care` 0.7.3 tried to talk to `topkg` 0.7.4.

Should `tokpg-care` use an `==` dependency?

**Comment by dbuenzli** [comment]
It's a slip I should have updated `topkg-care.0.7.3`'s constraint when I released 0.7.4. But since I basically release in pair you are right I should rather use `=` than `>=` when I release.

**Comment by dbuenzli** [comment]
Will be fixed by https://github.com/ocaml/opam-repository/pull/6815 thanks for the report.
