### ISSUE TITLE
Debug build in `Dev compilation context.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#54]
Discussion about policies whether `debug` should be enabled in releases always ended up inconclusively. But were leaning towards that they should not.

For a long time I have relied on *not* having `true : debug` in my `_tags` and invoke build commands through a shell script for development which would add `-tag debug`. 

With `topkg`'s command set I think I can get rid of these scripts in most of my packages --- and in carcass' `topkg` bodies. But this problem remain. Here's a way to solve it: 

Add a `--debug` configuration key which, if unspecified, is determined according to build context (i.e. `true` if Dev and `false` on Pin and Release). The default build command will add the `-tag debug` according to whether the configuration key is enabled or not.

**Comment by samoht** [comment]
> Discussion about policies whether debug should be enabled in releases always ended up inconclusively. But were leaning towards that they should not.

The `debug` flag is now set unconditionally for opam's 4.03 compiler: https://github.com/ocaml/opam-repository/blob/master/compilers/4.03.0/4.03.0/4.03.0.comp#L6

@chambart added this recently, saying that this will not cause any harm.

**Comment by dbuenzli** [comment]
@samoht Thanks for the info. If that became the norm I think the same policy should be implemented in pre 4.03.0 switches.

**Comment by dbuenzli** [comment]
So given this I think that as far as topkg is concerned I'll simply add that `--debug` flag and have it to `true` if unspecified in any build context. The default `build` invocation will use `--tag debug` on `--debug true`.

**Comment by dbuenzli** [comment]
Added that the default value can be overriden via `TOPKG_CONF_DEBUG` env.
