### ISSUE TITLE
fail when command-line parameters are not recognised?

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#56]
See https://ci.appveyor.com/project/docker/datakit/build/1.0.112#L621

```
ocaml "pkg/pkg.ml" "build" "--pinned" "true" "--with-github" "disable"
```

Just went fine, but tried to build the github bindings instead of just failing to parse `disable`.

**Comment by dbuenzli** [comment]
It uses the default value, which is `true` for `with_pkg`s but yes maybe it should fail and you should use `github:installed`
