### ISSUE TITLE
How to install documentation / manpages

### ISSUE THREAD

**Issue by hhugo** [dbuenzli/topkg#6]
ocamlbuild provides rules to generate documentation directory from `*.odocl`files.
However, the target you must provide to ocamlbuild is not the directory itself:
`*.odocl -> *.docdir/index.html`
What are the options to install documentation with topkg + ocamlbuild ?

**Comment by dbuenzli** [comment]
For installing manpages you should simply add rules in `ocamlbuild` to build them. For the `html` docs installing the `cmti` will be enough in the future. I don't want to complicate the system with two passes. `topkg` is limited but if it works well for 95% of the cases it's fine to be limited.
