### ISSUE TITLE
Suggested approach for builds in an environment like opam-cross-windows

### ISSUE THREAD

**Issue by hcarty** [dbuenzli/topkg#61]
I'd like to be able to cross-compile libraries under [opam-cross-windows](https://github.com/whitequark/opam-cross-windows/) which use `topkg`.  I have had reasonable success with other libraries using the `OCAMLFIND_TOOLCHAIN`/`-toolchain` support in `ocamlfind`.

I'm not sure how to approach build a `topkg`-using library such as `fmt` though.  Do you have any suggestions on how to modify https://github.com/dbuenzli/fmt/blob/master/pkg/pkg.ml and similar package descriptions to work with this kind of cross-compilation environment?  Or is there a better approach to use in this case?

My current hack is to include `fmt.install` with in the opam repository and build `fmt` with:
```
build: [
  [
    "env" "OCAMLFIND_TOOLCHAIN=windows"
    "ocamlbuild" "-use-ocamlfind"
    "src/fmt.cma"     "src/fmt.cmxa"     "src/fmt.cmxs"
    "src/fmt_cli.cma" "src/fmt_cli.cmxa" "src/fmt_cli.cmxs"
    "src/fmt_tty.cma" "src/fmt_tty.cmxa" "src/fmt_tty.cmxs"
    "src/fmt_top.cma" "src/fmt_top.cmxa" "src/fmt_top.cmxs"
  ]
]
```

**Comment by dbuenzli** [comment]
Note sure I understand why you build the thing manually.  I think that the [approach](https://github.com/whitequark/opam-cross-android#porting-packages) @whitequark had with the old `topkg` scripts should still apply. 

Note also that in general `topkg` packages might lookup the result of `ocamlc -config`, the actual `ocamlc` that ends up being looked up should however by default go through `ocamlfind` aswell. There are various ways how this can be overriden though if you don't have `ocamlfind` see [here](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#tool).

**Comment by dbuenzli** [comment]
> might lookup the result of ocamlc -config

It's not *might* in fact it's *do*, e.g. to detect availability of native compilation and native dynlink.

**Comment by hcarty** [comment]
I may be missing something, but [this for example](https://github.com/whitequark/opam-cross-windows/blob/master/packages/tgls-windows.0.8.3.dev/opam#L16) approach does not work with the new `topkg` because the new approach `#require`s `topkg`.  The gross `env OCAMLFIND_TOOLCHAIN=windows ocaml pkg/pkg.ml` approach causes the findlib toplevel `#require`directive to look for a non-native Windows topkg rather than the (intended) native one.

**Comment by dbuenzli** [comment]
Mmmh indeed. 

Though I see solutions, I don't see any clean one (e.g. you could set `HOST_OS_OCAMLBUILD` to point to a script that essentially sets the `OCAMLFIND_TOOLCHAIN` variable and calls `ocamlbuild`). 

If you or @whitequark come up with a better solution that requires direct `topkg` support I'm willing to implement it.

**Comment by hcarty** [comment]
Thank you for the suggestion.  This seems to work, at least initially, based on a quick test with `fmt` on an Ubuntu host.

I saved this as `ocb-cross-windows` in the project's root directory:
```sh
#!/bin/bash
export OCAMLFIND_TOOLCHAIN=windows
ocamlbuild $@
```
and run this:
```sh
env HOST_OS_OCAMLBUILD=./ocb-cross-windows ocaml pkg/pkg.ml build
```
which gives:
```sh
fmt$ file _build/test/test.native 
_build/test/test.native: PE32+ executable (console) x86-64, for MS Windows
```

**Comment by dbuenzli** [comment]
Cool. It's my hope that with opam v2.0 you can define such env variables globally so that you won't have to fiddle with the `build:` section *at all*.

**Comment by whitequark** [comment]
That's really awful. Inserting intermediate scripts is fragile enough so that I won't merge such packages (or write them myself). I haven't looked closer yet but, unless something can be made about it, opam-cross-* will resort to patching topkg instead.

**Comment by dbuenzli** [comment]
I don't see how much more fragile this makes than all the hacks for cross-compilation indirections you already have in place... 

In any case `topkg` offers you a principled way of doing this by gathering all these tools in a single directory and use the `HOST_OS_XBIN` environment variable which will allow you to solve for all the `topkg` packages in bulk.

Now if you prefer patching hacks, please do.

**Comment by dbuenzli** [comment]
> Inserting intermediate scripts is fragile enough so that I won't merge such packages (or write them myself).

Btw. the new `topkg` as a package approach shows that your `OCAMLFIND_TOOLCHAIN` technique is as fragile as all the rest.

**Comment by whitequark** [comment]
> Btw. the new topkg as a package approach shows that your OCAMLFIND_TOOLCHAIN technique is as fragile as all the rest.

I completely agree, `OCAMLFIND_TOOLCHAIN` is an awful hack whose only purpose is to make oasis work. Any buildsystem less than completely fossilized ought to be able to pass the `-toolchain` option itself.

**Comment by hcarty** [comment]
The shell wrapper works for my local packaging for now.

I'm not sure how to adapt `ocamlbuild` to pass `-toolchain` - it looks like the `ocamlfind` calls are fairly baked-in to `ocamlbuild` in its current state.  Any changes made to `ocamlbuild` upstream would be limited OCaml 4.03.0 and later since previous OCaml versions have `ocamlbuild` included with the compiler.

**Comment by dbuenzli** [comment]
@hcarty I'll let you figure out how to proceed with @whitequark at that point, since apparently he knows how to patch `topkg` to solve the problem.
