### ISSUE TITLE
lint: after pre-build hooks?

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#66]
If you generate `pkg/META` from `pkg/META.in`, run `topkg lint` will say:

```
$ topkg lint
[ OK ] File CHANGES.md is present.
[ OK ] File LICENSE.md is present.
[ OK ] File README.md is present.
[ OK ] File opam is present.
[FAIL] File pkg/META is present.
[FAIL] lint META file pkg/META:
       ocamlfind lint messages:
       pkg/META: No such file
[ OK ] lint OPAM file opam.
[ OK ] OPAM file opam and _tags dependency check.
[FAIL] lint /Users/thomas/git/irmin-watcher failure: 2 errors.
```

Which is true but incomplete. I have tried to tweak various things to make `tokpkg` happy but without success.

**Comment by samoht** [comment]
See https://github.com/samoht/irmin-watcher/pull/3 for an unsatisfactory work-around

**Comment by dbuenzli** [comment]
Linting operates on the contents of a distribution. Since you are creating the `META` file at distribution *build* time nothing can be done. Can't you simply disable the lint with [`Pkg.meta_file`](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALmeta_file).

**Comment by samoht** [comment]
it still try to read `pkg/META` for some random reasons.

**Comment by dbuenzli** [comment]
Well then do a `metas:[]` and add `Pkg.lib "pkg/META"` to install it manually (assuming your build system knows how to build it).

**Comment by dbuenzli** [comment]
(if you build it in a pre-hook not you can say [~built:false] and it will look it up in the source tree).

**Comment by samoht** [comment]
The workaround seem to work.

**Comment by dbuenzli** [comment]
It's not really a workaround, it all makes sense... when you declare a `meta_file` it is supposed to exist. 

I'm closing this since linting at distribution at build time doesn't really make sense, if something is wrong it's already too late... 

We could of course do it if we are in `Dev` mode, but in general I want to minimize tool behaviour differences according to build context; it avoids suprises, we already had some...

**Comment by samoht** [comment]
> I'm closing this since linting a distribution at build time doesn't really make sense, if something is wrong it's already too late...

Well the issue appears as well when you run the distribution phase, as it runs the liting and fail. But yes, I guess it's kind of ok.

**Comment by dbuenzli** [comment]
> Well the issue appears as well when you run the distribution phase, as it runs the liting and fail.

No it doesn't if you set `metas:[]`, no META file will be linted since there is no META file declared (if this doesn't behave as such please reopen).
