### ISSUE TITLE
`topkg clean` does not work on windows

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#67]
```
ocaml pkg/pkg.ml clean
mkdir 'C:\OCaml64\home\thomas\git\irmin-watcher\_build'
rm -Rf 'C:\OCaml64\home\thomas\git\irmin-watcher\_build'
rm: cannot remove 'C:\OCaml64\home\thomas\git\irmin-watcher\_build/_log': Device or resource busy
```

**Comment by dbuenzli** [comment]
If you invoke this with `./pkg/pkg.ml clean -v -v` you'll see that I'm simply using `ocamlbuild -clean` here (and removing PKG.install) manually. So this should be filed with `ocamlbuild` I guess. Reopen if that's not the case.
