### ISSUE TITLE
lint: support `package(pkg1 pkg2 ... pkgn)` in `_tags`

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#69]
currently the `package(pkg1 pkg2 ... pkgn)` syntax is not supported by `topkg lint`:

```
$ cat _tags
true: bin_annot, debug
true: warn_error(+1..49), warn(A-4-41-44)
true: short_paths

true: package(cstruct astring fmt hex logs lwt ocamlgraph re uri crc mstruct)
```

```
$ topkg lint
[FAIL] File opam and _tags dependency check:
       astring: opam present but _tags absent
       fmt: opam present but _tags absent
       hex: opam present but _tags absent
       logs: opam present but _tags absent
       lwt: opam present but _tags absent
       mstruct: opam present but _tags absent
       ocamlgraph: opam present but _tags absent
       cstruct astring fmt hex logs lwt ocamlgraph re uri crc mstruct: _tags present but opam absent
```

**Comment by gasche** [comment]
This is not new, but I kind of forgot about this. ocamlbuild just passes the argument of its `package` tag to ocamlfind, and it happens that ocamlfind supports both `-package 'foo bar'` and `-package 'foo, bar'`. I don't think that people should rely on it.

**Comment by dbuenzli** [comment]
Aaaah why did you remove people should not rely on this... was about to close the issue...

**Comment by gasche** [comment]
I thought this was an undocumented feature of ocamlfind, but then I looked at ocamlfind documentation and it is rather clearly document. I'm not completely sure whether I should just advise people not to rely on it, or document it myself in the documentation of the `package` tag -- I'm opting for the later, because preventing people from using convenient stuff is usually a lost battle. What do you think?

**Comment by hcarty** [comment]
@gasche Is there a standard format within ocamlbuild for parameterized tags which take multiple parameters?

Aside from being shorter in the file, the main use I've had for multiple arguments in a single `package(...)` is preprocessors when order of application matters.

**Comment by dbuenzli** [comment]
> because preventing people from using convenient stuff is usually a lost battle. What do you think?

Seems right. I'd be glad if you defined a standard though like @hcarty suggests, e.g. either mandatory comma (potentially surrdounded by space) or only spaces.

**Comment by samoht** [comment]
I am happy to follow the standard in my packages, but would be great if it was short. e.g. I'm becoming quite fond of `package(foo bar)`.

**Comment by dbuenzli** [comment]
I would also prefer and be keen to use the one @samoht mention.

**Comment by dbuenzli** [comment]
Since it wasn't hard to support both through `String.fields` separators can be whitespace or commas.
