### ISSUE TITLE
multi-packages release?

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#73]
What is the expected workflow for multi-packages release? I am struggling a little bit at the moment to understand how this should work.

- it doesn't seem by default to re-use the same tarball, but if you use different tarballs you cannot easily upload them on the same milestone whith the toy GitHub delegate.
- `topkg opam pkg --dist-name <foo> --dist-file <bar>` doesn't seem to do what I want, e.g. it seems to discard my choice of `dist-name`.

```
$ topkg opam pkg --dist-name datakit-client --dist-file _build/datakit-0.6.0.tbz
Wrote OPAM package _build/datakit.0.6.0
```

Also, it's all very verbose, what I really dream is something like `topkg tag && topkg bistro --pkgs foo,bar,baz` or even `topkg tag && topkg bistro --all-pkgs`

**Comment by samoht** [comment]
Ha actually it seems to be a bug in `topkg opam pkg --dist-name <foo>`

```
$ topkg distrib --dist-name datakit-client
Cloning into '_build/datakit-client-0.6.0.build'...
done.
Wrote archive _build/datakit-client-0.6.0.tbz
[...]
Distribution for datakit-client 0.6.0
Commit b450d04b682c2acb866048971eed51785c6ff966
Archive _build/datakit-client-0.6.0.tbz
✔ 11:52 ~/git/datakit [master|⚑ 10] $ topkg opam pkg --dist-name datakit-client
Wrote OPAM package _build/datakit.0.6.0
```

**Comment by samoht** [comment]
Not sure why I was so confused, but using the `-n <name>` option worked much better.

**Comment by dbuenzli** [comment]
Just for the record the release process for multi-package for a single tarball is described in the documentation [here](http://erratique.ch/software/topkg/doc/Topkg#multiopam).
