### ISSUE TITLE
topkg publish dies with ocamlbuild plugins

### ISSUE THREAD

**Issue by pqwy** [dbuenzli/topkg#80]
If there are magic command line arguments necessary to get `myocamlbuild.ml` to compile -- like it referencing extra modules given by `-plugin-tag` -- `topkg publish` will bomb out because doc generation doesn't reuse the build command line.

With the up-and-coming glorious era of OCamlbuild plugins published, and distributed, on a **massive** scale, this should be re-thought.

**Comment by dbuenzli** [comment]
Yes it's because of the ad-hoc support to publish docs (see https://github.com/dbuenzli/topkg/issues/24). `topkg publish doc` dies because it tries to invoke `ocamlbuild` [by itself](https://github.com/dbuenzli/topkg/blob/c75bff90117daef97cfe93c7506b70a0dd95e9a7/src-bin/doc.ml#L14-L17) rather than try to reuse the `ocamlbuild` invocation you may have specified in your `pkg.ml` file (since `topkg` is build system agnostic). 

A work around it to simply replace `topkg publish` by `topkg publish distrib` and proceed with the release process.

**Comment by dbuenzli** [comment]
@pqwy mentions it should just be a matter of adding the `-no-plugin` line to that invocation.

**Comment by pqwy** [comment]
Yeah, #81 does it.

It's a bit hacky. But not terribly, given how doc building fits in with the rest.

**Comment by dbuenzli** [comment]
Fixed by  9582ee06740482

**Comment by samoht** [comment]
This fix seems to break doc generation when you have a custom `myocamlbuild.ml` right? I don't see how add `-no-plugin` is helping with the original problem.

**Comment by samoht** [comment]
See #93 for a continuation of this PR.

**Comment by dbuenzli** [comment]
Why doesn't @pqwy's solution work. I don't consider this https://github.com/mirage/ocaml-github/pull/176/commits/65c1a17f24938a0544b7d72da60a50b1706a8a67 to be a solution. `topkg doc` should build the docs and that's all.

**Comment by samoht** [comment]
Which solution?

I don't understand what this PR is solving. With that commit in, I get:

```
$ topkg build
[ ... ]
$ topkg doc
 topkg doc
File "_tags", line 5, characters 6-16:
Warning: the tag "no-plugin" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
ocamlfind ocamlc -c -g -principal -strict-sequence -package 'cohttp uri cohttp.lwt-core yojson atdgen stringext tls' -package lwt -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/github_s.cmi lib/github_s.mli
Solver failed:
  Ocamlbuild knows of no rules that apply to a target named lib/Github_t.ml. This can happen if you ask Ocamlbuild to build a target with the wrong extension (e.g. .opt instead of .native) or if the source files live in directories that have not been specified as include directories.
Backtrace:
[...]
```

`topkg doc` works fine if I remove the `-no-plugin` flag, either by reverting that PR or by applying #93 + `--build-flags ''`.

**Comment by samoht** [comment]
It also works when using `-just-plugin` instead of `-no-plugin`. Not sure what this option does exactly. I'll try to see if I can repro @pqwy's case.

**Comment by samoht** [comment]
Hum ok I understand the initial problem better now. My issue si that I need to read (and compile) `myocamlbuild.ml` to create the implicit rules for the generated `.mli` files. A solution is to run the `ocamlbuild` command in the build directory instead of running it at the toplevel, so all the generated files are there (with `-no-hygiene`).  Would it be something that you could consider including?

**Comment by samoht** [comment]
Last edit: actually if `_build/myocamlbuild` exists, calling `_build/myocamlbuild` instead of `ocamlbuild` seems to work.

**Comment by pqwy** [comment]
We have a total, head-on collision of requirements here.

I require additional `ocamlfind` libs in my `myocamlbuild.ml`. The only way to add libs to its compilation is to pass extra arguments to `ocamlfind` (`-plugin-tag`, see the various discussions around why `_tags` doesn't come into play). Since the doc-command is ad-hoc, in that is does not derive from the build-command, it does not share the extra arguments, so `ocamlbuild` bombs out in the first step -- compiling its plugin. A way around that is to completely ignore `myocamlbuild`. `-no-plugin` does just that, and is an argument that `ocamlbuild` internally uses when invoking *itself*, as compiled from `myocamlbuild`, to stop the cycle.

Use case is anything that uses `ocb-stubblr`.

You have extra generated files, and the rules to build them are registered in your `myocamlbuild.ml`. Clearly, if one skips the plugin, the rules to materialize a bunch of files are missing.

Use case is really any custom rules for generating `ml` files, which are in turn input for the doc step.

This change completely and comprehensively disabled `myocamlbuild.ml` processing during doc generation.

A way out of the stalemate is to actually rethink how the doc-command should relate to the build-command, while keeping `topkg`'s semi-ocamlbuild-agnostic structure. Whoever comes up with a good redesign of how `topkg` derives its doc-command gets to fix this, I guess. A telltale mark of a *good redesign* is that you don't have to repeat things in `pkg.ml`. Another one is that you don't have to pass empty arguments to anything.

**Comment by samoht** [comment]
@pqwy but can't you just build before building the docs? e.g. in your case, `topkg build && topkg doc` should just work right? The first invocation will build `_build/myocamlbuil`, the second one will just re-use that.

**Comment by dbuenzli** [comment]
So I discussed this with @pqwy in person and I'll simply try to reuse the build command specified in the `pkg/pkg.ml` file which should make it work for everyone.

**Comment by samoht** [comment]
Any update on this? It is unfortunately not possible to generate docs with 0.8.1 if using a myocamlbuid.ml file. Not sure what is the recommended way to workaround that: use odig and do some magic during `topkg publish`?

**Comment by dbuenzli** [comment]
@samoht @pqwy could you please confirm me that the new `topkg doc` works for both of you by trying with:

```
opam pin add --dev-repo cmdliner
opam pin add --dev-repo topkg 
opam pin add --dev-repo topkg-care
```

**Comment by samoht** [comment]
@dbuenzli I confirm that it works well on https://github.com/samoht/ocaml-github/tree/topkg. Thanks!
