### ISSUE TITLE
Debugger support destroys `ocb-stubblr` by accident

### ISSUE THREAD

**Issue by pqwy** [dbuenzli/topkg#82]
Since 2bf815d3784c726529964fca4b66dad7d1e01579, `.clib` files are read by `topkg`.

But any OCamlbuild target can be generated on-demand. `ocb-stubblr` works by generating alternative-target clibs on-demand; the `.clib` files mentioned in `pkg.ml` and meant for different Mirage runtimes, xen or freestanding, **do not exist in the source directory**.

**Comment by dbuenzli** [comment]
Well I guess `ocb-stubblr`'s authors didn't [read the documentation](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALclib) we are talking about files not targets. What about `ocb-stubblr` providing its own high-level combinators for this ?

**Comment by pqwy** [comment]
Is this the intended new semantics? Because it used to be the case that `Pkg.clib` did not require the file to exist, prior to the invocation of the build system. As a side-effect of debugger support, it now does. That's a pretty big change.

Of course I can always make my own equivalent of `Pkg.clib`.

**Comment by dbuenzli** [comment]
The purpose of these combinators is to reuse the *files* from `ocamlbuild`. The documentation talks about *files* not targets.

**Comment by pqwy** [comment]
I see.
