### ISSUE TITLE
Needs a way to pass -toolchain option to ocamlfind

### ISSUE THREAD

**Issue by whitequark** [dbuenzli/topkg#86]
topkg used to be very friendly to cross-compilation as it did not use ocamlfind itself; it was enough to simply run `env OCAMLFIND_TOOLCHAIN=xxx ocaml pkg/build.ml` to build a package. Now this is not the case as setting OCAMLFIND_TOOLCHAIN will break the `#require` directive. topkg should therefore handling passing it to ocamlbuild itself.

**Comment by dbuenzli** [comment]
If I trust @whitequark this should be solved by 05685ce095c88721e731c9c8158
