### ISSUE TITLE
lint `.mllib`

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/topkg#88]
I just created my first package with `topkg` and `carcass`. (If you want to see how I (mis)used it: [pkg.ml](https://gitlab.com/edwintorok/ocaml-anycache/blob/master/pkg/pkg.ml) [.carcass](https://gitlab.com/edwintorok/dot_carcass))
It definitely improves on some aspects of the build, testing and publishing process, here are some mistakes that I made that slipped through `topkg lint`. (apologies for  the issue flood)

I had this unsaved change in my editor, and got no complaints from `topkg` or `opam`, I only noticed the subpackage is missing when inspecting the documentation with `odig`:

```diff
--- a/pkg/pkg.ml
+++ b/pkg/pkg.ml
@@ -23,6 +23,8 @@ let () =
   Ok [
     (let api = ["Anycache";"Anycache_pendinglimit"] in
      Pkg.mllib ~api "src/anycache.mllib");
+    Pkg.mllib ~cond:lwt "src/anycache_lwt.mllib";
+    Pkg.mllib ~cond:async "src/anycache_async.mllib";
```

Might be useful to warn about any extra `.mllib` files that don't have corresponding `Pkg.mllib` calls.

**Comment by dbuenzli** [comment]
> I just created my first package with topkg and carcass. (If you want to see how I (mis)used it: pkg.ml .carcass)

Before you invest too much time in it, I just warn you that carcass is at the moment unsupported software. I hope to release it soon but I'll switch the flesh and carcass files to sexps. 

> Might be useful to warn about any extra .mllib files that don't have corresponding Pkg.mllib calls.

Maybe, on the other hand I expect these things to be catched quickly.

**Comment by dbuenzli** [comment]
This is similar to #91. Here again it's not exactly clear it's a good idea, e.g. when you have [multiple packages](http://erratique.ch/software/topkg/doc/Topkg.html#multiopam) for a single the description may not see all `.mllib` files in each configuration.
