### ISSUE TITLE
lint or automatically generate .merlin

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/topkg#89]
In the spirit of https://github.com/dbuenzli/topkg/issues/18 automatically generating or linting the `PKG` line of `.merlin` could be useful.
(OTOH it is not something that impacts end-users, it is just one more place to manually update when updating a package's dependencies so this may not belong in `topkg`)

**Comment by dbuenzli** [comment]
I'm not really into the generation business, I see generation as indirection layers to fix design issues in the tooling. I prefer if we try to fix the issues themselves. 

In that spirit I rather think that merlin should be a bit smarter at configuring itself. A good hint that we can do much better is to run `odig guess-deps _build` on one of your builds, but this is all work in progress.

As far as linting `.merlin` is concerned I'm not to keen on writing my own half broken `.merlin` file parser. Also the linting is more there to ensure that your release will be correct and having an out of sync `.merlin` is not really a concern for install correctness.

**Comment by edwintorok** [comment]
Agreed this probably belongs in https://github.com/the-lambda-church/merlin/issues/240
