### ISSUE TITLE
lint: `.ml` or `.mli` files that are not part of any executables or libraries

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/topkg#91]
There is probably a bit of overlap between `carcass` and `topkg` here.
When I use `carcass ocaml/mod src` to create a new module as part of an existing library (as opposed to `carcass ocamlbuild/lib src` to create the library in the first place) it might be useful for `topkg lint` to show that a file that is part of version control (one would opefully notice files that aren't added to version control with `git status`) is not yet used in any way during a build.
Of course it might be just some module used for building an executable, in which case it doesn't have to be declared anywhere, however inspecting `_build/_log` would tell you which files are used.

**Comment by dbuenzli** [comment]
I'm a little bit unsure about this one. It seems a bit difficult to make it reliable and there may be legitimate reasons why you may have `.ml` and `.mli` lying around that are in your repo.

**Comment by edwintorok** [comment]
Hmm yeah conditional builds might be one such reason, when you run `topkg distrib` you may not have everything installed to test your package in its "full" configuration, and then some files may be unused. (Otherwise you can add your files to a mllib, to a test, or as a doc file, I don't know if this feature would annoy people more than it would help though).

**Comment by dbuenzli** [comment]
I'm not convinced by the proposal.
