### ISSUE TITLE
topkg-care: support opam-lib.1.3.0

### ISSUE THREAD

**Issue by avsm** [dbuenzli/topkg#97]
opam-lib.1.3.0 is the [migration package](https://opam.ocaml.org/blog/opam-lib-1-3/) for opam2 support. It would be very handy if topkg-care could publish a version that is compatible with this new version, as I currently have to uninstall `topkg-care` as I do the migration of other users.

**Comment by dbuenzli** [comment]
Could someone explain to me what `opam-lib` 1.3.0 brings to the table besides apparently breaking packages that will be broken anyways again by opam v2.0 ?

**Comment by dbuenzli** [comment]
It seems that migrating to the dependency less `opam-file-format` is going to be a real pain as it is too low-level. I'll try to see what kind of changes `opam-format` entails for now.
